=== bparrello/seedtk_test/source/ERDB/ERDB_DBD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Database">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Title"/>
                <xs:element ref="Issues" minOccurs="0"/>
                <xs:element ref="Notes"/>
                <xs:element ref="Regions"/>
                <xs:element ref="Diagram"/>
                <xs:element ref="Entities"/>
                <xs:element ref="Relationships" minOccurs="0" />
                <xs:element ref="Shapes" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Title" type="xs:string"/>
    <xs:element name="Issues" type="xs:string"/>
    <xs:element name="Regions">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="Region"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Region">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Notes"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Diagram">
        <xs:complexType>
            <xs:attribute name="editable" use="required" type="xs:integer"/>
            <xs:attribute name="fontSize" use="required" type="xs:integer"/>
            <xs:attribute name="height" use="required" type="xs:integer"/>
            <xs:attribute name="ratio" use="required" type="xs:decimal"/>
            <xs:attribute name="size" use="required" type="xs:integer"/>
            <xs:attribute name="width" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Entities">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Entity"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Entity">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="DisplayInfo"/>
                <xs:element ref="Notes"/>
                <xs:element minOccurs="0" ref="Asides"/>
                <xs:element minOccurs="0" ref="Fields"/>
                <xs:element minOccurs="0" ref="FulltextIndexes" />
                <xs:element minOccurs="0" ref="Indexes"/>
            </xs:sequence>
            <xs:attribute name="autonumber" type="xs:integer"/>
            <xs:attribute name="keyType" use="required" type="dataType"/>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Indexes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Index"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Index">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Notes"/>
                <xs:element ref="IndexFields"/>
            </xs:sequence>
            <xs:attribute name="unique" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FulltextIndexes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="FulltextIndex"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FulltextIndex">
        <xs:complexType>
          <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" ref="UseField"/>
          </xs:sequence>
          <xs:attribute name="type" type="textIndexType"/>
          <xs:attribute name="name" type="xs:string" />
          <xs:attribute name="path" type="xs:string" />
          <xs:attribute name="in_result" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UseField">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" />
          <xs:attribute name="field" type="xs:string"/>
          <xs:attribute name="in_result" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    <xs:element name="Relationships">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Relationship"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Relationship">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="DisplayInfo"/>
                <xs:element ref="Notes"/>
                <xs:element ref="Asides" minOccurs="0" />
                <xs:element ref="Fields" minOccurs="0" />
                <xs:element minOccurs="0" ref="FromIndex"/>
                <xs:element minOccurs="0" ref="ToIndex"/>
                <xs:element minOccurs="0" ref="Indexes" />
            </xs:sequence>

            <xs:attribute name="arity" use="required" type="arityType"/>
            <xs:attribute name="converse" use="required" type="xs:string"/>
            <xs:attribute name="from" use="required" type="xs:string"/>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="to" use="required" type="xs:string"/>
            <xs:attribute name="embedded" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FromIndex">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Notes"/>
                <xs:element ref="IndexFields"/>
            </xs:sequence>
            <xs:attribute name="unique" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ToIndex">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Notes"/>
                <xs:element ref="IndexFields"/>
            </xs:sequence>
            <xs:attribute name="unique" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Shapes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Shape"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Shape">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="DisplayInfo"/>
                <xs:element ref="Notes"/>
                <xs:element ref="Asides" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="from" use="required" type="xs:string"/>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="to" use="required" type="xs:string"/>
            <xs:attribute name="type" use="required" type="shapeType"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Notes" type="xs:string"/>
    <xs:element name="DisplayInfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="RegionInfo"/>
            </xs:sequence>
            <xs:attribute name="caption"/>
            <xs:attribute name="col" type="xs:decimal"/>
            <xs:attribute name="connected" type="xs:integer"/>
            <xs:attribute name="fixed" type="xs:integer"/>
            <xs:attribute name="row" type="xs:decimal"/>
            <xs:attribute name="theme" use="required" type="themeType"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="RegionInfo">
        <xs:complexType>
            <xs:attribute name="caption"/>
            <xs:attribute name="col" type="xs:decimal"/>
            <xs:attribute name="fixed" type="xs:integer"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="row" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Asides" type="xs:string"/>
    <xs:element name="Fields">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Field"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Field">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Notes"/>
                <xs:element minOccurs="0" ref="Asides"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="relation" type="xs:string"/>
            <xs:attribute name="special" type="xs:string"/>
            <xs:attribute name="type" use="required" type="dataType"/>
            <xs:attribute name="null" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="IndexFields">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="IndexField"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="IndexField">
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="order" type="orderType"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="shapeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="diamond"/>
            <xs:enumeration value="rectangle"/>
            <xs:enumeration value="biarrow"/>
            <xs:enumeration value="arrow"/>
            <xs:enumeration value="oval"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="themeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="black"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="brown"/>
            <xs:enumeration value="cyan"/>
            <xs:enumeration value="gray"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="ivory"/>
            <xs:enumeration value="navy"/>
            <xs:enumeration value="purple"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="violet"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="arityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MM"/>
            <xs:enumeration value="1M"/>
            <xs:enumeration value="11"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="textIndexType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="field" />
        <xs:enumeration value="related_field" />
      </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="orderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ascending"/>
            <xs:enumeration value="descending"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="counter"/>
            <xs:enumeration value="countVector"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dna"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="hash-string"/>
            <xs:enumeration value="image"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="link"/>
            <xs:enumeration value="long-string"/>
            <xs:enumeration value="proteinData"/>
            <xs:enumeration value="rectangle"/>
            <xs:enumeration value="semi-boolean"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="text"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== bparrello/seedtk_test/source/ERDB/ShrubDBD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://bio-macpro-1.mcs.anl.gov/~parrello/FIG/Html/ERDB_DBD.xsd">
	<Title>SEED Bioinformatics Database</Title>
	<Notes>[p]The SEED database manages bio-informatics data imported from
		exchange files. It contains information that can be used to derive
		subsystem spreadsheets and support annotation of genomes. The
		annotation is three-tiered: for each protein, we recognize a
		[i]privileged[/i] annotation, which is curated by a human expert,
		a [i]projected[/i] annotation which is computed by annotation software,
		and a [i]non-priviliged[/i] annotation which is proposed by the
		user
		community.[/p]
		[p]The diagram colors indicate the general category of data.[/p]
		[list]
		[b]Red[/b]
		Genome group: includes all taxonomy and sequence data.[*]
		[b]Blue[/b]
		Annotation group: includes the subsystems and all the functions and
		roles.[*]
		[b]Green[/b] Feature group: includes features, protein sequences,
		and related publications.[*]
		[b]Navy[/b] Chemistry group: includes reactions and compounds.
		[/list]
	</Notes>
	<Diagram height="800" width="600" ratio="0.7" size="90"
		fontSize="12" editable="0" />
	<Entities>
		<Entity name="Genome" keyType="string">
			<DisplayInfo theme="red" col="3" row="2" />
			<Notes>A genome represents a specific organism with DNA, or a
				specific meta-genome. All DNA sequences in the database belong to
				genomes.
			</Notes>
			<Fields>
				<Field name="core" type="boolean">
					<Notes>TRUE if this is a core genome, else FALSE.
					Annotation data is projected from core genomes.</Notes>
				</Field>
				<Field name="name" type="string">
					<Notes>Full genus/species/strain name of the genome, occasionally
						containing notes from the uploader.
					</Notes>
				</Field>
				<Field name="dna-size" type="counter">
					<Notes>Number of base pairs in the genome.</Notes>
				</Field>
				<Field name="contigs" type="int">
					<Notes>Number of contigs for this genome.</Notes>
				</Field>
				<Field name="md5-identifier" type="string">
					<Notes>MD5 identifier for this genome, for comparison with genomes
						in other databases. The MD5 is computed by taking the MD5s of
						the contigs, lexically sorting them, joining them together with
						commas, and computing a hex MD5 of the result.
					</Notes>
				</Field>
				<Field name="gc-content" type="float">
					<Notes>Percent GC content present in the genome's DNA.</Notes>
				</Field>
				<Field name="contig-file" type="long-string">
					<Notes>Name of the file containing the genome's contig FASTA,
						relative to the repository root.
					</Notes>
				</Field>
			</Fields>
			<Indexes>
				<Index>
					<Notes>This index allows searching for genomes by name.</Notes>
					<IndexFields>
						<IndexField name="name" order="ascending" />
					</IndexFields>
				</Index>
				<Index>
					<Notes>This index allows searching for genomes by MD5 identifier.
					</Notes>
					<IndexFields>
						<IndexField name="md5-identifier" ordering="ascending" />
					</IndexFields>
				</Index>
				<Index>
					<Notes>This index presents the core genomes first in
					sequence.</Notes>
					<IndexFields>
						<IndexField name="core" ordering="descending" />
					</IndexFields>
				</Index>
			</Indexes>
		</Entity>
		<Entity name="Contig" keyType="string">
			<DisplayInfo theme="red" col="1" row="4" />
			<Notes>A contig is a contiguous sequence of base pairs belonging to
				a single genome. The key of the contig is the genome ID followed
				by a colon and then the contig ID. The contig's DNA information is
				located in a flat file on disk named "contigs.fa" in the
				directory named by the parent genome.
			</Notes>
			<Fields>
				<Field name="length" type="counter">
					<Notes>Number of base pairs in the contig.</Notes>
				</Field>
				<Field name="md5-identifier" type="string">
					<Notes>MD5 identifier of this contig, for comparison with contigs
						in other databases. This is a standard hex MD5 of the contig
						DNA sequence.
					</Notes>
				</Field>
			</Fields>
			<Indexes>
				<Index>
					<Notes>This index allows searching for contigs by MD5 identifier.
					</Notes>
					<IndexFields>
						<IndexField name="md5-identifier" order="ascending" />
					</IndexFields>
				</Index>
			</Indexes>
		</Entity>
		<Entity name="Feature" keyType="string">
			<DisplayInfo theme="green" col="3" row="4" />
			<Notes>A feature (sometimes also called a gene) is a part of a
				genome that is of special interest. Features may be spread across
				multiple DNA sequences (contigs) of a genome, but never across more
				than one genome. Each feature in the database has a unique FIG
				ID that functions as its ID in this table.
			</Notes>
			<Fields>
				<Field name="feature-type" type="string">
					<Notes>Code indicating the type of this feature. Among the
						codes currently supported are "peg" for a protein encoding
						gene, "bs" for a binding site, "opr" for an operon, and so
						forth.
					</Notes>
				</Field>
				<Field name="sequence-length" type="counter">
					<Notes>Number of base pairs in this feature.</Notes>
				</Field>
				<Field name="alias" type="string" relation="FeatureAlias">
					<Notes>An alternative name for the feature. These are frequently
						ambiguous or incomplete.
					</Notes>
				</Field>
			</Fields>
			<Indexes>
				<Index>
					<Notes>This index is used to find a feature by alias name.</Notes>
					<IndexFields>
						<IndexField name="alias" order="ascending" />
					</IndexFields>
				</Index>
			</Indexes>
		</Entity>
		<Entity name="Protein" keyType="string">
			<DisplayInfo theme="green" col="4" row="6" />
			<Notes>A protein sequence is a specific sequence of amino acids.
				Unlike a DNA sequence, a protein sequence does not belong to a
				genome. Identical proteins generated by different genomes are
				stored as a single Protein instance. The key is a hex MD5
				hash code computed from the protein letter sequence.
			</Notes>
			<Fields>
				<Field name="sequence" type="text">
					<Notes>The sequence contains the letters corresponding to
						the protein's amino acids.
					</Notes>
				</Field>
			</Fields>
		</Entity>
		<Entity name="TaxonomicGrouping" keyType="string">
			<DisplayInfo row="2" col="1" caption="Taxonomic\nGrouping"
				theme="red" />
			<Notes>A taxonomic grouping is a segment of the classification for
				an organism. Taxonomic groupings are organized into a strict
				hierarchy by the IsGroupContaining relationship.
			</Notes>
			<Fields>
				<Field name="domain" type="boolean">
					<Notes>TRUE if this is a domain grouping, else FALSE.</Notes>
				</Field>
				<Field name="hidden" type="boolean">
					<Notes>TRUE if this is a hidden grouping, else FALSE. Hidden
						groupings are not typically shown in a lineage list.
					</Notes>
				</Field>
				<Field name="scientific-name" type="string">
					<Notes>Primary scientific name for this grouping. This is the name
						used when displaying a taxonomy.
					</Notes>
				</Field>
				<Field name="alias" type="string" relation="TaxonomicGroupingAlias">
					<Notes>Alternate name for this grouping. A grouping
						may have many alternate names. The scientific name should also
						be in this list.
					</Notes>
				</Field>
			</Fields>
			<Indexes>
				<Index>
					<Notes>This index allows the user to find a particular
						taxonomic grouping by name. Because the scientifc name is
						also an alias, there is no index on scientific name.
					</Notes>
					<IndexFields>
						<IndexField name="alias" order="ascending" />
					</IndexFields>
				</Index>
			</Indexes>
		</Entity>
		<Entity name="GenomeSet" keyType="string">
			<DisplayInfo theme="red" caption="Genome Set" row="2"
				col="5" />
			<Notes>A genome set is a named group of related genomes.</Notes>
			<Asides>Each genome set consists of genomes that use highly similar
				ribosomal small subunits. Two genomes are in the same set if they
				have a similarity of 97% or greater in subunits of length 1000 or
				more.
			</Asides>
		</Entity>
		<Entity name="Function" keyType="int" autonumber="1">
			<DisplayInfo theme="blue" row="6" col="2" />
			<Notes>A function is a set of roles that represent the effects of a
				protein. Most functions consist of a single role, but many can have two or three
				roles.
			</Notes>
			<Fields>
				<Field name="statement" type="long-string">
					<Notes>Text of the function, consisting of the roles strung together
					in sequence with separator characters in between.</Notes>
				</Field>
				<Field name="sep" type="char">
					<Notes>Separator character for this function's roles. [b]/[/b] for
					multiple roles by different domains, [b]@[/b] for multiple
					roles by the same domain, or [b];[/b] when the function performs
					one of several roles but the precise one cannot be determined.
					For a single-function role, [b]@[/b] is used.</Notes>
				</Field>
				<Field name="checksum" type="hash-string">
					<Notes>Checksum for this function, formed by normalizing the roles,
					sorting them lexically, joining them with tab characters and prefixing
					the characters, then computing an MD5.</Notes>
				</Field>
			</Fields>
			<Indexes>
				<Index unique="1">
					<Notes>This index allows searching for functions by the checksum string.</Notes>
					<IndexFields>
						<IndexField name="checksum" order="ascending" />
					</IndexFields>
				</Index>
			</Indexes>
		</Entity>
		<Entity name="Role" keyType="int" autonumber="1">
			<DisplayInfo theme="blue" row="8" col="3" />
